#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1

module load foss
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

# Analyze Hamiltonian trajectory for the extended dipole approximation
time ../../NISE_2017/bin/NISE inputAnalyseExtended

