#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1

module load foss
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

# Do circular dichroism with extended dipole approximation
# and projection on the B850 chromophores
time ../../NISE_2017/bin/NISE inputCD_ED

