#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=8

module load foss
setenv OMP_NUM_THREADS 8
setenv MKL_NUM_THREADS 1

setenv WD $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

time ~/git/NISE_2017/bin/NISE inputCD

#cp *.log $WD
#cp *.dat $WD
