#!/bin/csh
#SBATCH --job-name LH2_Absorption_dipole
#SBATCH --nodes=1
#SBATCH --ntasks=1

module load foss
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

setenv WD $SLURM_SUBMIT_DIR

time ../../NISE_2017/bin/NISE input1Ddipole

