#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=0-10:30:00

module load foss
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

setenv WD $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

time ~/git/NISE_2017/bin/NISE inputPop

#cp *.log $WD
#cp *.dat $WD
