#!/bin/bash
#SBATCH --job-name LH2_Coarse_Grained_2D
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=0-06:00:00

module load foss

setenv OMP_NUM_THREADS 8
setenv MKL_NUM_THREADS 8

time ../../NISE_2017/bin/NISE input2DCG
../../NISE_2017/bin/2DFFT input2DCG

