#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1

module load intel FFTW
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

setenv WD $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

time ~/git/NISE_dev/NISE_2017/bin/NISE inputLum

#cp *.log $WD
#cp *.dat $WD
