#!/bin/bash
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=0-01:00:00

#module load foss
module load foss

setenv OMP_NUM_THREADS 4
setenv MKL_NUM_THREADS 4

setenv WD $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

../../NISE_2017/bin/NISE inputPop

#cp *.log $WD
#cp *.dat $WD
