#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=4

module load foss

setenv OMP_NUM_THREADS 4
setenv MKL_NUM_THREADS 4

setenv WD $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

time ../../NISE_2017/bin/NISE inputPopdipole

#cp *.log $WD
#cp *.dat $WD
