#!/usr/bin/env bash
#SBATCH --job-name FMO_MCFRET
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=0-02:00:00

# Load the modules that you also used when compiling the NISE code
module load foss

# Defining the number of OpenMP threads as done below is not needed on
# most clusters, but it cannot hurt.
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1

# Run the MCFRET calculation
time ../../../NISE_2017/bin/NISE inputMCFRET

