#!/bin/bash
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=0-01:00:00

#module load foss
#module load 2023.01 StdEnv
module load intel FFTW

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1

export WD=$SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

time ~/git/NISE_MCFRET2/NISE_2017/bin/NISE inputMCFRET

#cp *.log $WD
#cp *.dat $WD
