#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1

module load foss
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

# Run program in directory from where it was submitted
# First convert ASCII file to binary
../../NISE_2017/bin/translate inpTra
time ../../NISE_2017/bin/NISE input1D

