#!/bin/csh
#SBATCH --job-name NISE3_SFG
#SBATCH --nodes=1
#SBATCH --ntasks=1

module load foss
setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

#setenv WD $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module load Anaconda3
# Gemnerate a polarizability file
python make_Polarizability.bin.py 
# Run program in directory from where it was submitted
time ../../NISE_2017/bin/NISE inputSFG

